COLOR_DARK_CHARCOAL = "#2c2c2c"
COLOR_LIGHT_GRAY = "#e0e0e0"
COLOR_DEEP_RED = "#8b0000"

BG_COLOR = COLOR_DARK_CHARCOAL

HEIGHT = 800
WIDTH = 1200

FONT_FAMILY = "Courier New"

CAMERA_SIZE_WIDTH = 300
CAMERA_SIZE_HEIGHT = 200

ROOM_WIDTH = 600
ROOM_HEIGHT = 400
ROOM_PATH = "static/mainRoom1.jpeg"

OFFICER_PATH = "static/officer_no_bg.png"
OFFICER_HEIGHT = 500
OFFICER_Y_OFFSET = OFFICER_HEIGHT
OFFICER_X_OFFSET = 100

TALKING_HEIGHT = 100
TALKING_WIDTH = 600
TALKING_X = 70
TALKING_Y = HEIGHT - 200

TEXT_DELAY = 50